CREATE TABLE IF NOT EXISTS files(
    file_id SERIAL PRIMARY KEY,
    file_content BYTEA NOT NULL,
    file_type VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);