export enum StudyType {
    OTHER = "OTHER",
    PRESCRIPTION = "PRESCRIPTION",
    RADIOGRAPHY = "RADIOGRAPHY",
    LABORATORY_RESULT = "LABORATORY_RESULT",
    ULTRASOUND = "ULTRASOUND",
    MRI = "MRI",
    ELECTROCARDIOGRAM = "ELECTROCARDIOGRAM",
    VACCINATION_RECORD = "VACCINATION_RECORD",
};
